#!/usr/bin/env python3
"""
convert.py — Rex Yap Property Listings Converter
将 listings_manager.xlsx 转换为 listingsData.js
Usage: python convert.py
"""

import json, sys, argparse
from pathlib import Path
from datetime import datetime

try:
    import openpyxl
except ImportError:
    print("❌ 请先安装: pip install openpyxl")
    sys.exit(1)

COL = {
    "status":1,"badge":2,"icon":3,"image":4,
    "title_zh":5,"title_en":6,"title_ms":7,
    "feat_zh":8,"feat_en":9,"feat_ms":10,
    "price_zh":11,"price_en":12,"price_ms":13,
    "wa_zh":14,"wa_en":15,"wa_ms":16,
}

SHEETS = {
    "rentals":     "🏠 出租房源 Rentals",
    "forSale":     "🏡 出售房源 For Sale",
    "newLaunches": "🏗️ 新楼盘 New Launches",
}

DATA_START_ROW = 5  # rows 1-4 are headers/hints in the Excel template

WA = {
    "rentals": {
        "zh": lambda t,p,f: f"你好Rex，我想了解出租房源：{t}（{p}）。\n{f}\n能否发送照片？谢谢！",
        "en": lambda t,p,f: f"Hi Rex, I'm interested in the rental: {t} ({p}).\n{f}\nCould you send photos? Thanks!",
        "ms": lambda t,p,f: f"Hai Rex, saya berminat dengan sewa: {t} ({p}).\n{f}\nBoleh hantar gambar? Terima kasih!",
    },
    "forSale": {
        "zh": lambda t,p,f: f"你好Rex，我想了解出售房源：{t}（{p}）。\n{f}\n能否发送照片？谢谢！",
        "en": lambda t,p,f: f"Hi Rex, I'm interested in the property: {t} ({p}).\n{f}\nCould you send photos? Thanks!",
        "ms": lambda t,p,f: f"Hai Rex, saya berminat dengan hartanah: {t} ({p}).\n{f}\nBoleh hantar gambar? Terima kasih!",
    },
    "newLaunches": {
        "zh": lambda t,p,f: f"你好Rex，我想了解新楼盘：{t}。\n{f}\n能否发送项目资料？谢谢！",
        "en": lambda t,p,f: f"Hi Rex, I'm interested in the new launch: {t}.\n{f}\nCould you send project details? Thanks!",
        "ms": lambda t,p,f: f"Hai Rex, saya berminat dengan projek: {t}.\n{f}\nBoleh hantar butiran projek? Terima kasih!",
    },
}

def cv(ws, row, col):
    v = ws.cell(row=row, column=col).value
    return str(v).strip() if v is not None else ""

def parse_sheet(ws, category):
    items = []
    for row in range(DATA_START_ROW, ws.max_row + 1):
        status   = cv(ws, row, COL["status"]).lower()
        title_zh = cv(ws, row, COL["title_zh"])
        if not title_zh or status == "inactive":
            continue
        title_en = cv(ws, row, COL["title_en"]) or title_zh
        title_ms = cv(ws, row, COL["title_ms"]) or title_zh
        feat_zh  = cv(ws, row, COL["feat_zh"])
        feat_en  = cv(ws, row, COL["feat_en"]) or feat_zh
        feat_ms  = cv(ws, row, COL["feat_ms"]) or feat_zh
        price_zh = cv(ws, row, COL["price_zh"])
        price_en = cv(ws, row, COL["price_en"]) or price_zh
        price_ms = cv(ws, row, COL["price_ms"]) or price_zh
        image    = cv(ws, row, COL["image"]) or None
        badge    = cv(ws, row, COL["badge"]) or "🏠"
        icon     = cv(ws, row, COL["icon"]) or "fa-home"
        tpl      = WA[category]
        wa_zh    = cv(ws, row, COL["wa_zh"]) or tpl["zh"](title_zh, price_zh, feat_zh)
        wa_en    = cv(ws, row, COL["wa_en"]) or tpl["en"](title_en, price_en, feat_en)
        wa_ms    = cv(ws, row, COL["wa_ms"]) or tpl["ms"](title_ms, price_ms, feat_ms)
        items.append({
            "badge": badge, "icon": icon, "image": image,
            "title":    {"zh": title_zh, "en": title_en, "ms": title_ms},
            "features": {"zh": feat_zh,  "en": feat_en,  "ms": feat_ms},
            "price":    {"zh": price_zh, "en": price_en, "ms": price_ms},
            "waText":   {"zh": wa_zh,    "en": wa_en,    "ms": wa_ms},
        })
    return items

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--excel",  default="listings_manager.xlsx")
    parser.add_argument("--output", default="listingsData.js")
    args = parser.parse_args()

    excel_path = Path(args.excel)
    if not excel_path.exists():
        print(f"❌ 找不到文件: {excel_path}")
        sys.exit(1)

    print(f"📖 读取: {excel_path}")
    wb   = openpyxl.load_workbook(excel_path)
    data = {}
    total = 0
    for key, sheet_name in SHEETS.items():
        if sheet_name not in wb.sheetnames:
            print(f"⚠️  找不到工作表: '{sheet_name}' — 跳过")
            data[key] = []
            continue
        items = parse_sheet(wb[sheet_name], key)
        data[key] = items
        total += len(items)
        print(f"  ✅ {sheet_name}: {len(items)} 条")

    js = f"""// listingsData.js — 由 convert.py 自动生成，请勿手动编辑
// Auto-generated by convert.py — DO NOT EDIT MANUALLY
// 最后更新 Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}

const listingsData = {json.dumps(data, ensure_ascii=False, indent=2)};
"""
    Path(args.output).write_text(js, encoding="utf-8")
    print(f"\n✅ 完成！{total} 条房源 → {args.output}")

if __name__ == "__main__":
    main()
