// listingsData.js — 由 convert.py 自动生成，请勿手动编辑
// Auto-generated by convert.py — DO NOT EDIT MANUALLY
// 最后更新 Last updated: 2026-05-12 08:21

var listingsData = {
  "rentals": [
    {
      "badge": "✨ 新上市 New Listing",
      "icon": "fa-building",
      "image": "condo_kk_1.jpg",
      "title": {
        "zh": "海滨公寓 | 亚庇",
        "en": "海滨公寓 | 亚庇",
        "ms": "海滨公寓 | 亚庇"
      },
      "features": {
        "zh": "📍 3房2卫 · 面积 950 sqft · 游泳池·健身室·BBQ区 · 🔒 24小时保安 · CCTV监控 · 等级3门禁",
        "en": "📍 3BR 2BA · 950 sqft · 游泳池·健身室·BBQ区 · 🔒 24小时保安 · CCTV监控 · 等级3门禁",
        "ms": "📍 3Bilik 2Bilik Air · 950 sqft · 游泳池·健身室·BBQ区 · 🔒 24小时保安 · CCTV监控 · 等级3门禁"
      },
      "price": {
        "zh": "💰 月租 RM 2,800",
        "en": "💰 Monthly Rent RM 2,800",
        "ms": "💰 Sewa Bulanan RM 2,800"
      },
      "waText": {
        "zh": "你好Rex，我想了解出租房源：海滨公寓 | 亚庇（💰 月租 RM 2,800）。\n📍 3房2卫。\n能否发送该房源的照片？谢谢！",
        "en": "Hi Rex, I'm interested in the rental: 海滨公寓 | 亚庇 (💰 月租 RM 2,800).\n📍 3BR 2BA.\nCould you send photos? Thanks!",
        "ms": "Hai Rex, saya berminat dengan sewa: 海滨公寓 | 亚庇 (💰 月租 RM 2,800).\n📍 3Bilik 2Bilik Air.\nBoleh hantar gambar? Terima kasih!"
      }
    },
    {
      "badge": "✨ 业主急售 Urgent",
      "icon": "fa-building",
      "image": null,
      "title": {
        "zh": "Tiara ParkHome| Karjang",
        "en": "Tiara ParkHome| Karjang",
        "ms": "Tiara ParkHome| Karjang"
      },
      "features": {
        "zh": "📍 2房2卫 · 面积 110 sqft · 🔒 24小时保安 · CCTV监控 · 等级6门禁",
        "en": "📍 2BR 2BA · 110 sqft · 🔒 24小时保安 · CCTV监控 · 等级6门禁",
        "ms": "📍 2Bilik 2Bilik Air · 110 sqft · 🔒 24小时保安 · CCTV监控 · 等级6门禁"
      },
      "price": {
        "zh": "💰 月租 RM 1,800",
        "en": "💰 Monthly Rent RM 1,800",
        "ms": "💰 Sewa Bulanan RM 1,800"
      },
      "waText": {
        "zh": "你好Rex，我想了解出租房源：Tiara ParkHome| Karjang（💰 月租 RM 1,800）。\n📍 2房2卫。\n能否发送该房源的照片？谢谢！",
        "en": "Hi Rex, I'm interested in the rental: Tiara ParkHome| Karjang (💰 月租 RM 1,800).\n📍 2BR 2BA.\nCould you send photos? Thanks!",
        "ms": "Hai Rex, saya berminat dengan sewa: Tiara ParkHome| Karjang (💰 月租 RM 1,800).\n📍 2Bilik 2Bilik Air.\nBoleh hantar gambar? Terima kasih!"
      }
    }
  ],
  "forSale": [
    {
      "badge": "✨ 新上市 New Listing",
      "icon": "fa-building",
      "image": "condo_kk_1.jpg",
      "title": {
        "zh": "海滨公寓 | 亚庇",
        "en": "海滨公寓 | 亚庇",
        "ms": "海滨公寓 | 亚庇"
      },
      "features": {
        "zh": "📍 3房2卫 · 面积 950 sqft · 游泳池·健身室·BBQ区 · 🔒 24小时保安 · CCTV监控 · 等级3门禁",
        "en": "📍 3BR 2BA · 950 sqft · 游泳池·健身室·BBQ区 · 🔒 24小时保安 · CCTV监控 · 等级3门禁",
        "ms": "📍 3Bilik 2Bilik Air · 950 sqft · 游泳池·健身室·BBQ区 · 🔒 24小时保安 · CCTV监控 · 等级3门禁"
      },
      "price": {
        "zh": "💰 售价 RM 2,800",
        "en": "💰 Selling Price RM 2,800",
        "ms": "💰 Harga Jualan RM 2,800"
      },
      "waText": {
        "zh": "你好Rex，我想了解出售房源：海滨公寓 | 亚庇（💰 售价 RM 2,800）。\n📍 3房2卫。\n能否发送照片？谢谢！",
        "en": "Hi Rex, I'm interested in the property: 海滨公寓 | 亚庇 (💰 售价 RM 2,800).\n📍 3BR 2BA.\nCould you send photos? Thanks!",
        "ms": "Hai Rex, saya berminat dengan hartanah: 海滨公寓 | 亚庇 (💰 售价 RM 2,800).\n📍 3Bilik 2Bilik Air.\nBoleh hantar gambar? Terima kasih!"
      }
    }
  ],
  "newLaunches": [
    {
      "badge": "✨ 新上市 New Listing",
      "icon": "fa-building",
      "image": "condo_kk_1.jpg",
      "title": {
        "zh": "海滨公寓 | 亚庇",
        "en": "海滨公寓 | 亚庇",
        "ms": "海滨公寓 | 亚庇"
      },
      "features": {
        "zh": "📍 3房2卫 · 面积 950 sqft · 游泳池·健身室·BBQ区 · 🔒 24小时保安 · CCTV监控 · 等级3门禁",
        "en": "📍 3BR 2BA · 950 sqft · 游泳池·健身室·BBQ区 · 🔒 24小时保安 · CCTV监控 · 等级3门禁",
        "ms": "📍 3Bilik 2Bilik Air · 950 sqft · 游泳池·健身室·BBQ区 · 🔒 24小时保安 · CCTV监控 · 等级3门禁"
      },
      "price": {
        "zh": "🔥 欢迎咨询价格",
        "en": "🔥 Price Upon Request",
        "ms": "🔥 Harga atas Permintaan"
      },
      "waText": {
        "zh": "你好Rex，我想了解新楼盘：海滨公寓 | 亚庇。\n能否发送项目照片/户型图？谢谢！",
        "en": "Hi Rex, I'm interested in the new launch: 海滨公寓 | 亚庇.\nCould you send project photos/floor plans? Thanks!",
        "ms": "Hai Rex, saya berminat dengan projek baru: 海滨公寓 | 亚庇.\nBoleh hantar gambar projek/pelan lantai? Terima kasih!"
      }
    }
  ]
};
