// listingsData.js — 由 convert.py 自动生成，请勿手动编辑
// Auto-generated by convert.py — DO NOT EDIT MANUALLY
// 最后更新 Last updated: 2026-05-11 12:55

const listingsData = {
  "rentals": [
    {
      "badge": "🏢 Condo 公寓",
      "icon": "fa-home",
      "image": "Tiara ParkHome| Karjang",
      "title": {
        "zh": "2",
        "en": "2",
        "ms": "110"
      },
      "features": {
        "zh": "",
        "en": "24小时保安",
        "ms": "CCTV监控"
      },
      "price": {
        "zh": "等级6门禁",
        "en": "1800",
        "ms": "业主急售 Urgent"
      },
      "waText": {
        "zh": "=IFERROR(_xlfn.IFS(B5=\"🏢 Condo 公寓\",\"fa-building\",B5=\"🏠 Apartment 单位\",\"fa-home\",B5=\"🌿 即租即住\",\"fa-home\",B5=\"🌿 近国际学校\",\"fa-school\",B5=\"📌 商业旺铺\",\"fa-store\",B5=\"🌟 海景豪宅\",\"fa-water-ladder\",B5=\"📈 投资优选\",\"fa-chart-line\",B5=\"🏞️ 花园住宅\",\"fa-tree\",B5=\"🌟 2026全新地标\",\"fa-drafting-compass\",B5=\"📈 海外投资优选\",\"fa-globe\",B5=\"🌆 核心地段\",\"fa-city\",B5=\"🔥 限时优惠\",\"fa-fire\",B5=\"✅ 永久产权\",\"fa-certificate\",B5=\"🏅 高回报\",\"fa-medal\",B5=\"🏖️ 度假胜地\",\"fa-umbrella-beach\",B5=\"🏫 学区优选\",\"fa-graduation-cap\",B5=\"🛣️ 交通便利\",\"fa-road\",B5=\"🔑 即买即住\",\"fa-key\"),\"fa-home\")",
        "en": "=IF(D5<>\"\",D5,\"\")",
        "ms": "=IF(D5<>\"\",SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(D5,\"亚庇\",\"Kota Kinabalu\"),\"公寓\",\"Condo\"),\"排屋\",\"Terrace\"),\"别墅\",\"Villa\"),\"店铺\",\"Shop\"),\"新山\",\"Johor Bahru\"),\"市中心\",\"City Centre\"),\"高级\",\"Premium\"),\"单位\",\"Unit\"),\"住宅\",\"Residence\"),\"\")"
      }
    }
  ],
  "forSale": [],
  "newLaunches": []
};
