// listingsData.js — 由 convert.py 自动生成，请勿手动编辑
// Auto-generated by convert.py — DO NOT EDIT MANUALLY
// 最后更新 Last updated: 2026-04-30 08:38

const listingsData = {
  "rentals": [],
  "forSale": [
    {
      "badge": "🔑 即买即住",
      "icon": "fa-water-ladder",
      "image": "codo_1.jpeg",
      "title": {
        "zh": "Tiara ParkHomes | Kajang",
        "en": "Tiara ParkHomes | Kajang",
        "ms": "Tiara ParkHomes | Kajang"
      },
      "features": {
        "zh": "📍 3房2卫 · 无边泳池 · 永久地契 · 独立花园",
        "en": "📍 3BR 2BA · Infinity Pool · Freehold · Private Garden",
        "ms": "📍 3Bilik 2Bilik Air · Kolam Renang · Milikan Kekal · Taman Persendirian"
      },
      "price": {
        "zh": "💰 售价 RM 320,000",
        "en": "💰 Selling Price RM 320,000",
        "ms": "💰 Harga Jualan RM 320,000"
      },
      "waText": {
        "zh": "你好Rex，我想了解出售房源：Tiara ParkHomes | Kajang（💰 售价 RM 320,000）。\n📍 3房2卫 · 无边泳池 · 永久地契 · 独立花园\n能否发送照片？谢谢！",
        "en": "Hi Rex, I'm interested in the property: Tiara ParkHomes | Kajang (💰 Selling Price RM 320,000).\n📍 3BR 2BA · Infinity Pool · Freehold · Private Garden\nCould you send photos? Thanks!",
        "ms": "Hai Rex, saya berminat dengan hartanah: Tiara ParkHomes | Kajang (💰 Harga Jualan RM 320,000).\n📍 3Bilik 2Bilik Air · Kolam Renang · Milikan Kekal · Taman Persendirian\nBoleh hantar gambar? Terima kasih!"
      }
    }
  ],
  "newLaunches": []
};
